"""
Setup configuration for CineAIStudio package
"""

from setuptools import setup, find_packages

with open("README.md", "r", encoding="utf-8") as fh:
    long_description = fh.read()

setup(
    name="CineAIStudio",
    version="0.2.0",
    author="agions",
    author_email="agions@qq.com",
    description="Professional AI Video Editor",
    long_description=long_description,
    long_description_content_type="text/markdown",
    url="https://github.com/agions/CineAIStudio",
    packages=find_packages(),
    classifiers=[
        "Development Status :: 4 - Beta",
        "Intended Audience :: Developers",
        "License :: OSI Approved :: MIT License",
        "Operating System :: OS Independent",
        "Programming Language :: Python :: 3",
        "Programming Language :: Python :: 3.8",
        "Programming Language :: Python :: 3.9",
        "Programming Language :: Python :: 3.10",
        "Programming Language :: Python :: 3.11",
        "Topic :: Multimedia :: Video",
        "Topic :: Software Development :: Libraries :: Python Modules",
    ],
    python_requires=">=3.8",
    install_requires=[
        "PyQt6>=6.4.0",
        "numpy>=1.21.0",
        "opencv-python>=4.5.0",
        "Pillow>=8.3.0",
        "requests>=2.26.0",
        "psutil>=5.8.0",
        "openai>=0.27.0",
        "ollama>=0.1.0",
        "qianwen>=0.1.0",
        "wenxin>=0.1.0",
        "zhipuai>=0.1.0",
        "ffmpeg-python>=0.2.0",
        "pydub>=0.25.0",
        "matplotlib>=3.4.0",
        "scipy>=1.7.0",
        "scikit-learn>=1.0.0",
        "torch>=1.10.0",
        "torchvision>=0.11.0",
        "transformers>=4.15.0",
        "datasets>=1.18.0",
        "accelerate>=0.5.0",
        "tensorboard>=2.7.0",
        "wandb>=0.12.0",
        "mlflow>=1.20.0",
        "optuna>=2.10.0",
        "ray>=1.9.0",
        "dask>=2021.10.0",
        "joblib>=1.1.0",
        "tqdm>=4.62.0",
        "click>=8.0.0",
        "rich>=10.0.0",
        "typer>=0.4.0",
        "pydantic>=1.8.0",
        "fastapi>=0.68.0",
        "uvicorn>=0.15.0",
        "sqlalchemy>=1.4.0",
        "alembic>=1.7.0",
        "redis>=3.5.0",
        "celery>=5.1.0",
        "kombu>=5.1.0",
        "pika>=1.2.0",
        "aiofiles>=0.7.0",
        "httpx>=0.21.0",
        "aioredis>=2.0.0",
        "asyncpg>=0.24.0",
        "pytest>=6.2.0",
        "pytest-cov>=2.12.0",
        "pytest-asyncio>=0.15.0",
        "black>=21.0.0",
        "isort>=5.9.0",
        "flake8>=3.9.0",
        "mypy>=0.910",
        "pre-commit>=2.15.0",
        "tox>=3.24.0",
        "sphinx>=4.2.0",
        "sphinx-rtd-theme>=1.0.0",
    ],
    extras_require={
        "dev": [
            "pytest>=6.2.0",
            "pytest-cov>=2.12.0",
            "pytest-asyncio>=0.15.0",
            "black>=21.0.0",
            "isort>=5.9.0",
            "flake8>=3.9.0",
            "mypy>=0.910",
            "pre-commit>=2.15.0",
            "tox>=3.24.0",
        ],
        "docs": [
            "sphinx>=4.2.0",
            "sphinx-rtd-theme>=1.0.0",
        ],
    },
    entry_points={
        "console_scripts": [
            "CineAIStudio=CineAIStudio.main:main",
        ],
    },
    include_package_data=True,
    zip_safe=False,
)
